### ISSUE TITLE
How To Use In Minecraft

### ISSUE THREAD

**Issue by bluaxd** [mhasanjb/ForceBindIP-Gui#10]
It is possible to use ForceBindIP in Minecraft? Because ForceBindIP only applies the connection for the launcher itself and not later for javaw.exe process.

**Comment by ixjb94** [comment]
@bluaxd Hey,
I guess you can, because i used it for Steam and not Dota2.exe.
So how can you check it?
it's quite simple, open Task Manager -> Performance, while the game is open,
then check if it is using the Network Interface bandwidth or not.
![image](https://user-images.githubusercontent.com/121232430/212539093-0003b541-e5e4-41d2-b3ea-ce688c0c3c23.png)

**Comment by bluaxd** [comment]
Nope, javaw.exe still using my WIFI connection instead Ethernet

**Comment by ixjb94** [comment]
@bluaxd 
Isn't it working if you just add javaw.exe to the ForceBindIP ?

**Comment by ixjb94** [comment]
@bluaxd
Isn't it working if you just add javaw.exe to the ForceBindIP ?

You can always use the Network Interface Metric trick,
 
Image 1
![metric1](https://user-images.githubusercontent.com/121232430/212569101-5a924cc6-3212-4783-a74f-b77db72af7e6.png)

Image 2
![metric2](https://user-images.githubusercontent.com/121232430/212569107-cb40663d-32c1-43d1-882d-21d39ce80b4d.png)

**Comment by bluaxd** [comment]
Doesn't work. Yeah but the issue is I need to open two Minecraft instance using different Network Interface

**Comment by ixjb94** [comment]
I guess you can use a sandbox and then open the sandbox with ForceBindIP.

**Comment by bluaxd** [comment]
Well new issue: Windows changes the metric automatically even I changed the values.
