### ISSUE TITLE
Trojan detected 

### ISSUE THREAD

**Issue by ongleehin** [mhasanjb/ForceBindIP-Gui#14]
Hi, there is trojan detected in you ForceBindIP-gui when i check it using virus total website

**Comment by ixjb94** [comment]
Hey @ongleehin ,
the reason is this function
```
Func GetFileDownload()

    If FileExists(@ScriptDir & "\ForceBindIP - Download.exe") Then; System64
		Return Null
	Else
		InetGet ( "https://github.com/ixjb94/ForceBindIP-Gui/releases/download/binary/ForceBindIP.-.Download.exe", "ForceBindIP - Download.exe" ) ; Download
	EndIf

EndFunc
```
this function is Downloading the downloader file (it's a file that downloads ForceBindIP and copy it to c:\ )
that's why it detects it as "Trojan Downloader",

You can build it yourself,
1- download [Autoit Script](https://www.autoitscript.com/site/autoit/downloads/)
2- right click on the script (ForceBindIP - Gui.au3) and click on "Compile Script"
